version: '3'

services:
  web:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./app/templates:/app/templates

  db:
    build:
      context: ./db
